### ISSUE TITLE
Document runner-manager learnings

### ISSUE THREAD

**Issue by tcarmet** [scality/runner-manager#172]
Note the learnings from a dev first experience developing with the runner manager and reflect them in the documentation.

**Comment by gaspardmoindrot** [comment]
Resources to include in the documentation under 'Supporting a new cloud provider':

- How the user communicates the desired parameters to the Manager, see `runner.vm_type.config["xxx"]`
  - Where they are specified -> `config_example.yml` for testing
    - Detail the important points of the file, such as tags and their uses
    - Emphasize that this is where the data to be used is specified, as it is not a public repository
  - The purpose of `schema.py`

- Refer to the documentation that specifies how to run the project locally
- Explain what the various components of the Runner class are (especially `vm_id`, `action_id`, and `vm_type`)

**Comment by tcarmet** [comment]
As discussed we will quickly add a couple of information that may have helped you in developing with the runner-manager.

Don't spend more than one hour.
