### ISSUE TITLE
Add metrics endpoint

### ISSUE THREAD

**Issue by lewismiddleton** [scality/runner-manager#625]
I'd like to scrape metrics about the internal runner-manager state. Specifically have it expose how many runners it's tracking in each of its runner groups.

This is useful because we've sometimes observed that AWS EC2 instances may get 'orphaned' meaning the runner-manager service has lost track of it and forgets to delete it. Monitoring these metrics would allow us to detect these 'orphaned' instances by alerting on when the number of EC2 machines != the tracked number of runners.

I propose using [Prometheus](https://prometheus.io/) instrumentation via the [prometheus-client library](https://pypi.org/project/prometheus-client). This will introduce a `/metrics` endpoint that is used for machine readable metrics. 

Are there any objections to this approach?

**Comment by tcarmet** [comment]
No objections, it would be a very much welcome contribution. 

Quick note about the orphan situation, we recently noticed that in our kubernetes manifests we made a mistake on the redis volume path which in result would not persist our data and create orphans every time redis would reboot. (if that's the method of deployment you are using, worth double checking).

**Comment by lewismiddleton** [comment]
I tried an implementation in #628 but I don't think that's the right approach. To get prometheus metrics, I'm now looking at something like dumping the Redis data as JSON using `get_runners()` upon request to `/groups/{name}/list`.

Then writing a custom prometheus exporter to consume that JSON and parse it into prometheus metrics.
